update mhtc_sch.metrics set "URL" = 'http://nces.ed.gov/nationsreportcard/naepdata' where "Name" = '4th Grade Student Performance Math';
update mhtc_sch.metrics set "URL" = 'http://nces.ed.gov/nationsreportcard/naepdata' where "Name" = '4th Grade Student Performance Science';
update mhtc_sch.metrics set "URL" = 'http://nces.ed.gov/nationsreportcard/naepdata' where "Name" = '8th Grade Student Performance Math';
update mhtc_sch.metrics set "URL" = 'http://nces.ed.gov/nationsreportcard/naepdata' where "Name" = '8th Grade Student Performance Science';
update mhtc_sch.metrics set "URL" = 'http://www.bea.gov/iTable/iTable.cfm?reqid=70&step=1&isuri=1&acrdn=1#reqid=70&step=5&isuri=1&7003=900&7004=naics&7001=1900&7002=1&7090=70' where "Name" = 'Annual Gross State Product in Chained $';
update mhtc_sch.metrics set "URL" = 'http://www.bea.gov/iTable/iTable.cfm?reqid=70&step=1&isuri=1&acrdn=1#reqid=70&step=5&isuri=1&7003=900&7004=naics&7001=1900&7002=1&7090=70' where "Name" = 'Annual Gross State Product Growth Rate';
update mhtc_sch.metrics set "URL" = 'http://www.nsf.gov/statistics/seind14/index.cfm/state-data/table.htm?table=33' where "Name" = 'Bachelors Degree Holders in Workforce';
update mhtc_sch.metrics set "URL" = 'KPMG/Tax Foundation' where "Name" = 'Capital Gains Tax Rate';
update mhtc_sch.metrics set "URL" = 'KPMG/State Tax Statutes' where "Name" = 'Corporate Income Tax Rate';
update mhtc_sch.metrics set "URL" = 'KPMG/CCH'	 where "Name" = 'Corporate Income Tax-Apportionment Method';
update mhtc_sch.metrics set "URL" = 'KPMG/CCH'	 where "Name" = 'Corporate Income Tax-Sourcing Rules';
update mhtc_sch.metrics set "URL" = 'Wanted Analytics and Monster Government Solutions' where "Name" = 'Hiring Difficulty for Technology Industries';
update mhtc_sch.metrics set "URL" = 'http://www.census.gov/hhes/www/income/data/statemedian' where "Name" = 'Median Household Income';
update mhtc_sch.metrics set "URL" = 'CCH State Tax Handbook/Tax Foundation/KPMG' where "Name" = 'Personal Income Tax';
update mhtc_sch.metrics set "URL" = 'http://factfinder.census.gov' where "Name" = 'Quality of Life: Average Commute Time';
update mhtc_sch.metrics set "URL" = 'E&Y' where "Name" = 'Research and Development Tax Credit ASC Rate';
update mhtc_sch.metrics set "URL" = 'E&Y' where "Name" = 'Research and Development Tax Credit Rate';
update mhtc_sch.metrics set "URL" = 'E&Y' where "Name" = 'Research and Development Tax Credit Refundability Rate';
update mhtc_sch.metrics set "URL" = 'http://www.eia.gov/electricity/monthly/epm_table_grapher.cfm?t=epmt_5_6_b' where "Name" = 'Retail Price of Electricity';
update mhtc_sch.metrics set "URL" = 'KPMG/Sales Tax Clearinghouse' where "Name" = 'Sales Tax Rate';
update mhtc_sch.metrics set "URL" = 'KPMG/Tax Foundation' where "Name" = 'State and Local Tax Burden as Percent of Personal Income';
update mhtc_sch.metrics set "URL" = 'KPMG/Tax Foundation' where "Name" = 'State and Local Tax Burden Per Capita in $';
update mhtc_sch.metrics set "URL" = 'http://taxfoundation.org/article/2015-state-business-tax-climate-index' where "Name" = 'State Business Tax Climate Index';
update mhtc_sch.metrics set "URL" = 'http://statetechandscience.org/stateTech.html' where "Name" = 'State Technology and Science Index';
update mhtc_sch.metrics set "URL" = 'http://nces.ed.gov/ipeds/datacenter' where "Name" = 'STEM-related Bachelors Degrees Awarded';                   	;
update mhtc_sch.metrics set "URL" = 'http://www.nsf.gov/statistics/seind14/index.cfm/state-data/table.htm?table=55' where "Name" = 'Tech Employment as Percent of Total Employment';
update mhtc_sch.metrics set "URL" = 'http://www.cnbc.com/id/101758236' where "Name" = 'Top States for Business';
update mhtc_sch.metrics set "URL" = 'http://www.nsf.gov/statistics/seind14/index.cfm/state-data/table.htm?table=55' where "Name" = 'Total Employment';
update mhtc_sch.metrics set "URL" = 'http://www.nsf.gov/statistics/seind14/index.cfm/state-data/table.htm?table=55' where "Name" = 'Total Tech Employment';
update mhtc_sch.metrics set "URL" = 'http://workforcesecurity.doleta.gov/unemploy/avg_employ.asp' where "Name" = 'UI Premium Per Employee';
update mhtc_sch.metrics set "URL" = 'http://data.bls.gov/oes'	 where "Name" = 'State Business Tax Climate Index';
update mhtc_sch.metrics set "URL" = 'http://www.bls.gov/web/laus/laumstrk.htm' where "Name" = 'Unemployment Rate';
