update mhtc_sch.metrics set "DisplayOrder" =  'reversed' where "Name" = 'State Technology and Science Index';
update mhtc_sch.metrics set "DisplayOrder" =  'reversed' where "Name" = 'Top States for Business';
update mhtc_sch.metrics set "DisplayOrder" =  'reversed' where "Name" = 'State Business Tax Climate Index';
update mhtc_sch.metrics set "DisplayOrder" =  'normal' where "Name" = 'STEM-related Bachelors Degrees Awarded';
update mhtc_sch.metrics set "DisplayOrder" =  'normal' where "Name" = '4th Grade Student Performance Math';
update mhtc_sch.metrics set "DisplayOrder" =  'normal' where "Name" = '4th Grade Student Performance Science';
update mhtc_sch.metrics set "DisplayOrder" =  'normal' where "Name" = '8th Grade Student Performance Math';
update mhtc_sch.metrics set "DisplayOrder" =  'normal' where "Name" = '8th Grade Student Performance Science';
update mhtc_sch.metrics set "DisplayOrder" =  'reversed' where "Name" = 'Hiring Difficulty for Technology Industries';
update mhtc_sch.metrics set "DisplayOrder" =  'normal' where "Name" = 'Bachelors Degree Holders in Workforce';
update mhtc_sch.metrics set "DisplayOrder" =  'reversed' where "Name" = 'Retail Price of Electricity';
update mhtc_sch.metrics set "DisplayOrder" =  'reversed' where "Name" = 'UI Premium Per Employee';
update mhtc_sch.metrics set "DisplayOrder" =  'reversed' where "Name" = 'Capital Gains Tax Rate';
update mhtc_sch.metrics set "DisplayOrder" =  'normal' where "Name" = 'Corporate Income Tax-Sourcing Rules';
update mhtc_sch.metrics set "DisplayOrder" =  'normal' where "Name" = 'Corporate Income Tax-Apportionment Method';
update mhtc_sch.metrics set "DisplayOrder" =  'reversed' where "Name" = 'Sales Tax Rate';
update mhtc_sch.metrics set "DisplayOrder" =  'reversed' where "Name" = 'Corporate Income Tax Rate';
update mhtc_sch.metrics set "DisplayOrder" =  'reversed' where "Name" = 'Personal Income Tax';
update mhtc_sch.metrics set "DisplayOrder" =  'reversed' where "Name" = 'State and Local Tax Burden as Percent of Personal Income';
update mhtc_sch.metrics set "DisplayOrder" =  'reversed' where "Name" = 'State and Local Tax Burden Per Capita in $';
update mhtc_sch.metrics set "DisplayOrder" =  'normal' where "Name" = 'Total Tech Employment';
update mhtc_sch.metrics set "DisplayOrder" =  'normal' where "Name" = 'Total Employment';
update mhtc_sch.metrics set "DisplayOrder" =  'normal' where "Name" = 'Tech Employment as Percent of Total Employment';
update mhtc_sch.metrics set "DisplayOrder" =  'reversed' where "Name" = 'Unemployment Rate';
update mhtc_sch.metrics set "DisplayOrder" =  'normal' where "Name" = 'Annual Gross State Product-Growth Rate';
update mhtc_sch.metrics set "DisplayOrder" =  'normal' where "Name" = 'Annual Gross State Product in Chained $';
update mhtc_sch.metrics set "DisplayOrder" =  'normal' where "Name" = 'Median Household Income';


update mhtc_sch.metrics set "DisplayOrder" =  	3	where "Name" = 	'State Technology and Science Index';
update mhtc_sch.metrics set "DisplayOrder" =  	1	where "Name" = 	'Top States for Business';
update mhtc_sch.metrics set "DisplayOrder" =  	2	where "Name" = 	'State Business Tax Climate Index';
update mhtc_sch.metrics set "DisplayOrder" =  	9	where "Name" = 	'STEM-related Bachelors Degrees Awarded';
update mhtc_sch.metrics set "DisplayOrder" =  	4	where "Name" = 	'4th Grade Student Performance Math';
update mhtc_sch.metrics set "DisplayOrder" =  	5	where "Name" = 	'4th Grade Student Performance Science';
update mhtc_sch.metrics set "DisplayOrder" =  	6	where "Name" = 	'8th Grade Student Performance Math';
update mhtc_sch.metrics set "DisplayOrder" =  	7	where "Name" = 	'8th Grade Student Performance Science';
update mhtc_sch.metrics set "DisplayOrder" =  	10	where "Name" = 	'Hiring Difficulty for Technology Industries';
update mhtc_sch.metrics set "DisplayOrder" =  	8	where "Name" = 	'Bachelors Degree Holders in Workforce';
update mhtc_sch.metrics set "DisplayOrder" =  	20	where "Name" = 	'Retail Price of Electricity';
update mhtc_sch.metrics set "DisplayOrder" =  	19	where "Name" = 	'UI Premium Per Employee';
update mhtc_sch.metrics set "DisplayOrder" =  	11	where "Name" = 	'Capital Gains Tax Rate';
update mhtc_sch.metrics set "DisplayOrder" =  	14	where "Name" = 	'Corporate Income Tax-Sourcing Rules';
update mhtc_sch.metrics set "DisplayOrder" =  	15	where "Name" = 	'Corporate Income Tax-Apportionment Method';
update mhtc_sch.metrics set "DisplayOrder" =  	18	where "Name" = 	'Sales Tax Rate';
update mhtc_sch.metrics set "DisplayOrder" =  	13	where "Name" = 	'Corporate Income Tax Rate';
update mhtc_sch.metrics set "DisplayOrder" =  	12	where "Name" = 	'Personal Income Tax';
update mhtc_sch.metrics set "DisplayOrder" =  	16	where "Name" = 	'State and Local Tax Burden as Percent of Personal Income';
update mhtc_sch.metrics set "DisplayOrder" =  	17	where "Name" = 	'State and Local Tax Burden Per Capita in $';
update mhtc_sch.metrics set "DisplayOrder" =  	22	where "Name" = 	'Total Tech Employment';
update mhtc_sch.metrics set "DisplayOrder" =  	21	where "Name" = 	'Total Employment';
update mhtc_sch.metrics set "DisplayOrder" =  	23	where "Name" = 	'Tech Employment as Percent of Total Employment';
update mhtc_sch.metrics set "DisplayOrder" =  	24	where "Name" = 	'Unemployment Rate';
update mhtc_sch.metrics set "DisplayOrder" =  	26	where "Name" = 	'Annual Gross State Product-Growth Rate';
update mhtc_sch.metrics set "DisplayOrder" =  	27	where "Name" = 	'Annual Gross State Product in Chained $';
update mhtc_sch.metrics set "DisplayOrder" =  	25	where "Name" = 	'Median Household Income';
